#!/usr/bin/env python

Import('env')
Import('env_modules')

env_taskflow = env_modules.Clone()
env_taskflow.Append(CXXFLAGS=['/std:c++17'])

# Godot's own source files
env_taskflow.add_source_files(env.modules_sources, "*.cpp")
