#!/usr/bin/env python

import glob

Import("env")
Import("env_modules")


env_materialx = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []
thirdparty_path = "#thirdparty/materialx/source/"
env_materialx.Prepend(CPPPATH=[thirdparty_path])
thirdparty_sources = Glob(thirdparty_path + "MaterialXCore/*.cpp")
thirdparty_sources += Glob(thirdparty_path + "MaterialXFormat/*.cpp") 
thirdparty_sources += Glob(thirdparty_path + "MaterialXGenShader/*.cpp")

env_materialx.Append(CPPDEFINES=["MATERIALX_MAJOR_VERSION=0"])
env_materialx.Append(CPPDEFINES=["MATERIALX_MINOR_VERSION=0"])
env_materialx.Append(CPPDEFINES=["MATERIALX_BUILD_VERSION=0"])

env_thirdparty = env_materialx.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)

env_materialx.add_source_files(env.modules_sources, "*.cpp")