#!/usr/bin/env python

Import('env')
Import('env_modules')

fem_fx_async = env_modules.Clone()

env_thirdparty = fem_fx_async.Clone()
env_thirdparty.add_source_files(env.modules_sources, Glob('#thirdparty/fem_fx_async/*.cpp'))

# Godot's own source files
fem_fx_async.add_source_files(env.modules_sources, "*.cpp")
