#!/usr/bin/env python

Import("env")
Import("env_modules")

env_betsy = env_modules.Clone()

# Thirdparty source files
thirdparty_dir = "thirdparty/betsy/include"
thirdparty_sources = [
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_betsy.Prepend(CPPPATH=[thirdparty_dir])
env_betsy.Prepend(CPPPATH="thirdparty/betsy/Dependencies/SDL/Windows/include")

env_thirdparty = env_betsy.Clone()
env_thirdparty.disable_warnings()
betsy_source = Glob("thirdparty/betsy/src/betsy/*.cpp")
env_thirdparty.add_source_files(env.modules_sources, betsy_source)
env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)

# Godot source files
env_betsy.add_source_files(env.modules_sources, "*.cpp")
