#!/usr/bin/env python

Import('env')
env.add_source_files(env.modules_sources, ["register_types.cpp", "simplex_noise.cpp", "noise_texture.cpp", "noise_texture_3d.cpp", "#thirdparty/misc/open-simplex-noise.c"])
